/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as FrotasRouteImport } from './routes/frotas'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as IndexRouteImport } from './routes/index'

const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const FrotasRoute = FrotasRouteImport.update({
  id: '/frotas',
  path: '/frotas',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compras': typeof ComprasRoute
  '/frotas': typeof FrotasRoute
  '/metas': typeof MetasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compras': typeof ComprasRoute
  '/frotas': typeof FrotasRoute
  '/metas': typeof MetasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compras': typeof ComprasRoute
  '/frotas': typeof FrotasRoute
  '/metas': typeof MetasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/compras' | '/frotas' | '/metas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compras' | '/frotas' | '/metas'
  id: '__root__' | '/' | '/compras' | '/frotas' | '/metas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComprasRoute: typeof ComprasRoute
  FrotasRoute: typeof FrotasRoute
  MetasRoute: typeof MetasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frotas': {
      id: '/frotas'
      path: '/frotas'
      fullPath: '/frotas'
      preLoaderRoute: typeof FrotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComprasRoute: ComprasRoute,
  FrotasRoute: FrotasRoute,
  MetasRoute: MetasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
